packages:
  - packages/mnx
  - packages/music-theory
  - packages/mnx-score
  - packages/notation-fonts
  - packages/notation-engine
  - packages/notation-react
  - packages/audio
  - apps/app
  - apps/web
  - tools/*
allowBuilds:
  esbuild: true
patchedDependencies:
  mnxconverter@1.2.0: patches/mnxconverter@1.2.0.patch
