// White mensural (Renaissance) subset: the note shapes, rests and mensuration
// signs of c.1400-1550 notation, from the same vendored Bravura outlines as
// manifest.ts so both families share advance widths and stem/staff geometry.
// Codepoints resolved from the SMuFL glyphnames registry against Bravura 1.482.
export const SOURCE_FONT = 'Bravura.otf';
export const SOURCE_VERSION = '1.482';
export const RENAMED_FAMILY = 'PolyhymniaMensural';

const MODERN = {
  gClef: 'E050',
  gClef8vb: 'E052',
  gClef8va: 'E053',
  cClef: 'E05C',
  fClef: 'E062',
  fClef8vb: 'E064',
  fClef8va: 'E065',
  gClefChange: 'E07A',
  cClefChange: 'E07B',
  fClefChange: 'E07C',
  timeSig0: 'E080',
  timeSig1: 'E081',
  timeSig2: 'E082',
  timeSig3: 'E083',
  timeSig4: 'E084',
  timeSig5: 'E085',
  timeSig6: 'E086',
  timeSig7: 'E087',
  timeSig8: 'E088',
  timeSig9: 'E089',
  timeSigCommon: 'E08A',
  timeSigCutCommon: 'E08B',
  noteheadDoubleWhole: 'E0A0',
  noteheadWhole: 'E0A2',
  noteheadHalf: 'E0A3',
  noteheadBlack: 'E0A4',
  flag8thUp: 'E240',
  flag8thDown: 'E241',
  flag16thUp: 'E242',
  flag16thDown: 'E243',
  flag32ndUp: 'E244',
  flag32ndDown: 'E245',
  flag64thUp: 'E246',
  flag64thDown: 'E247',
  restDoubleWhole: 'E4E2',
  restWhole: 'E4E3',
  restHalf: 'E4E4',
  restQuarter: 'E4E5',
  rest8th: 'E4E6',
  rest16th: 'E4E7',
  rest32nd: 'E4E8',
  rest64th: 'E4E9',
  augmentationDot: 'E1E7',
  accidentalFlat: 'E260',
  accidentalNatural: 'E261',
  accidentalSharp: 'E262',
  accidentalDoubleSharp: 'E263',
  accidentalDoubleFlat: 'E264',
  accidentalParensLeft: 'E26A',
  accidentalParensRight: 'E26B',
  tuplet0: 'E880',
  tuplet1: 'E881',
  tuplet2: 'E882',
  tuplet3: 'E883',
  tuplet4: 'E884',
  tuplet5: 'E885',
  tuplet6: 'E886',
  tuplet7: 'E887',
  tuplet8: 'E888',
  tuplet9: 'E889',
  tupletColon: 'E88A',
  repeatDot: 'E044',
  breathMarkComma: 'E4CE',
  caesura: 'E4D1',
} as const;

const MENSURAL = {
  mensuralGclef: 'E900',
  mensuralFclef: 'E903',
  mensuralCclef: 'E905',
  mensuralWhiteMaxima: 'E95C',
  mensuralWhiteLonga: 'E95D',
  mensuralWhiteBrevis: 'E95E',
  mensuralWhiteMinima: 'E95F',
  mensuralWhiteSemiminima: 'E960',
  mensuralWhiteFusa: 'E961',
  mensuralWhiteSemibrevis: 'E962',
  mensuralNoteheadMaximaWhite: 'E933',
  mensuralNoteheadLongaWhite: 'E937',
  mensuralNoteheadMinimaWhite: 'E93C',
  mensuralNoteheadSemiminimaWhite: 'E93D',
  mensuralRestMaxima: 'E9F0',
  mensuralRestLongaPerfecta: 'E9F1',
  mensuralRestLongaImperfecta: 'E9F2',
  mensuralRestBrevis: 'E9F3',
  mensuralRestSemibrevis: 'E9F4',
  mensuralRestMinima: 'E9F5',
  mensuralRestSemiminima: 'E9F6',
  mensuralRestFusa: 'E9F7',
  mensuralRestSemifusa: 'E9F8',
  mensuralProlation1: 'E910',
  mensuralProlation2: 'E911',
  mensuralProlation3: 'E912',
  mensuralProlation4: 'E913',
  mensuralProlation5: 'E914',
  mensuralProlation6: 'E915',
  mensuralProlation7: 'E916',
  mensuralProlation8: 'E917',
  mensuralProlation9: 'E918',
  mensuralProlation10: 'E919',
  mensuralProlation11: 'E91A',
  mensuralProlationCombiningDot: 'E920',
  mensuralProlationCombiningTwoDots: 'E921',
  mensuralProlationCombiningThreeDots: 'E922',
  mensuralProlationCombiningThreeDotsTri: 'E923',
  mensuralProlationCombiningDotVoid: 'E924',
  mensuralProlationCombiningStroke: 'E925',
  mensuralProportion1: 'E926',
  mensuralProportion2: 'E927',
  mensuralProportion3: 'E928',
  mensuralProportion4: 'E929',
  mensuralProportionMajor: 'E92B',
  mensuralProportionMinor: 'E92A',
  mensuralProportionProportioDupla1: 'E91C',
  mensuralProportionProportioDupla2: 'E91D',
  mensuralProportionProportioTripla: 'E91E',
  mensuralProportionProportioQuadrupla: 'E91F',
  mensuralProportionTempusPerfectum: 'E91B',
  mensuralTempusPerfectumHoriz: 'E92E',
  mensuralTempusImperfectumHoriz: 'E92F',
  mensuralModusPerfectumVert: 'E92C',
  mensuralModusImperfectumVert: 'E92D',
  mensuralCombStemUp: 'E93E',
  mensuralCombStemDown: 'E93F',
  mensuralCombStemUpFlagRight: 'E941',
  mensuralCombStemDownFlagRight: 'E942',
  mensuralCombStemUpFlagLeft: 'E943',
  mensuralCombStemDownFlagLeft: 'E944',
  mensuralCombStemUpFlagFlared: 'E945',
  mensuralCombStemDownFlagFlared: 'E946',
  mensuralCombStemUpFlagExtended: 'E947',
  mensuralCombStemDownFlagExtended: 'E948',
  mensuralCombStemUpFlagSemiminima: 'E949',
  mensuralCombStemDownFlagSemiminima: 'E94A',
  mensuralCombStemUpFlagFusa: 'E94B',
  mensuralCombStemDownFlagFusa: 'E94C',
  mensuralCombStemDiagonal: 'E940',
} as const;

export const GLYPHS: Record<string, string> = { ...MODERN, ...MENSURAL };

export const UNICODE_RANGES = Object.values(GLYPHS)
  .map((cp) => `U+${cp}`)
  .join(',');
