/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExercisesIntervalComparisonIndexRouteImport } from './routes/exercises/interval-comparison/index'
import { Route as ExercisesIntervalComparisonCustomRouteImport } from './routes/exercises/interval-comparison/custom'
import { Route as ExercisesIntervalComparisonLessonLessonIdRouteImport } from './routes/exercises/interval-comparison/lesson.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIntervalComparisonIndexRoute =
  ExercisesIntervalComparisonIndexRouteImport.update({
    id: '/exercises/interval-comparison/',
    path: '/exercises/interval-comparison/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesIntervalComparisonCustomRoute =
  ExercisesIntervalComparisonCustomRouteImport.update({
    id: '/exercises/interval-comparison/custom',
    path: '/exercises/interval-comparison/custom',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExercisesIntervalComparisonLessonLessonIdRoute =
  ExercisesIntervalComparisonLessonLessonIdRouteImport.update({
    id: '/exercises/interval-comparison/lesson/$lessonId',
    path: '/exercises/interval-comparison/lesson/$lessonId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises/interval-comparison/custom': typeof ExercisesIntervalComparisonCustomRoute
  '/exercises/interval-comparison/': typeof ExercisesIntervalComparisonIndexRoute
  '/exercises/interval-comparison/lesson/$lessonId': typeof ExercisesIntervalComparisonLessonLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises/interval-comparison/custom': typeof ExercisesIntervalComparisonCustomRoute
  '/exercises/interval-comparison': typeof ExercisesIntervalComparisonIndexRoute
  '/exercises/interval-comparison/lesson/$lessonId': typeof ExercisesIntervalComparisonLessonLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises/interval-comparison/custom': typeof ExercisesIntervalComparisonCustomRoute
  '/exercises/interval-comparison/': typeof ExercisesIntervalComparisonIndexRoute
  '/exercises/interval-comparison/lesson/$lessonId': typeof ExercisesIntervalComparisonLessonLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises/interval-comparison/custom'
    | '/exercises/interval-comparison/'
    | '/exercises/interval-comparison/lesson/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises/interval-comparison/custom'
    | '/exercises/interval-comparison'
    | '/exercises/interval-comparison/lesson/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/exercises/interval-comparison/custom'
    | '/exercises/interval-comparison/'
    | '/exercises/interval-comparison/lesson/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesIntervalComparisonCustomRoute: typeof ExercisesIntervalComparisonCustomRoute
  ExercisesIntervalComparisonIndexRoute: typeof ExercisesIntervalComparisonIndexRoute
  ExercisesIntervalComparisonLessonLessonIdRoute: typeof ExercisesIntervalComparisonLessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/interval-comparison/': {
      id: '/exercises/interval-comparison/'
      path: '/exercises/interval-comparison'
      fullPath: '/exercises/interval-comparison/'
      preLoaderRoute: typeof ExercisesIntervalComparisonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/interval-comparison/custom': {
      id: '/exercises/interval-comparison/custom'
      path: '/exercises/interval-comparison/custom'
      fullPath: '/exercises/interval-comparison/custom'
      preLoaderRoute: typeof ExercisesIntervalComparisonCustomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/interval-comparison/lesson/$lessonId': {
      id: '/exercises/interval-comparison/lesson/$lessonId'
      path: '/exercises/interval-comparison/lesson/$lessonId'
      fullPath: '/exercises/interval-comparison/lesson/$lessonId'
      preLoaderRoute: typeof ExercisesIntervalComparisonLessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesIntervalComparisonCustomRoute:
    ExercisesIntervalComparisonCustomRoute,
  ExercisesIntervalComparisonIndexRoute: ExercisesIntervalComparisonIndexRoute,
  ExercisesIntervalComparisonLessonLessonIdRoute:
    ExercisesIntervalComparisonLessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
